apiVersion: v1
kind: Service
metadata:
  name: cliente-service
spec:
  selector:
    app: cliente-service
  ports:
    - nodePort: 30001
      port: 8081
      protocol: TCP
      targetPort: 8081
  type: LoadBalancer
  externalIPs:
    - 1.2.4.120